name: Sync
'on':
  push:
    branches:
      - master

jobs:
  auto-pr:
    name: sync-label-dashboard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: pull-request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          destination_branch: "new-main"

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          head: master
          base: new-main
          title: "Auto PR: main to label-dashboard-init"

      # - name: Actually Checkout repository
      #   uses: desbravacloud/action-create-pull-requests@v1
      #   with:
      #     origin-branch: 'main'
      #     target-branch: 'new-main'
      #     custom-title: 'Auto PR: main to label-dashboard-init'
      #     custom-body: |
      #       This is an automated pull request to merge changes from `main` into `label-dashboard-init`.
      #
      #       Please review the changes and merge if appropriate.

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: auto-pr-main-to-label-dashboard
      #     base: new-main
      #     title: 'Auto PR: main to label-dashboard-init'
      #     body: |
      #       This is an automated pull request to merge changes from `main` into `label-dashboard-init`.
      #
      #       Please review the changes and merge if appropriate.
      #     labels: |
      #       automated
      #       sync
      #     draft: false
