name: Sync
'on':
  push:
    branches:
      - master

jobs:
  auto-pr:
    name: sync-label-dashboard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto-pr-main-to-label-dashboard
          base: new-main
          title: 'Auto PR: main to label-dashboard-init'
          body: |
            This is an automated pull request to merge changes from `main` into `label-dashboard-init`.
            
            Please review the changes and merge if appropriate.
          labels: |
            automated
            sync
          draft: false
